language: node_js
node_js:
  - '0.10'
env:
  global:
    - secure: apJaPfSA/ZxKEcp5bKhyRKQG1inAm/faWKatQriRZ7pJt93cPjhwnhbzcdT8CbP8mPLisdwdT6iMtjexLG37N9/jq0pnVFdy8vI1VX0ALEjRAKKp2jgIf3GHhtTVp478DkaNkKCX1IepVjYMMneqtX2LmLDBwXW7GHMESBNsn7PM2hvpsCc2JWfDpQNConD0X64n2T05Wr2ZmDSJzIFZh9XCc40ibyBLBhDphQkAMT2mPf0SU7Kyyv4zT9PglQoLV/I0XgKljb9Hp09DEeFNvYuz4v7NSlOVGzdN+KcZJ0Jw63gjU1KcxmKKKA7BSQLEkt1E2zuB/2tAvRXe4QtsYJFQGdn56ONhD4vT7QcCzngW9tgssLuClGUDUchL16W1aH1LNtKUaJURN08Kj5NlfMJbIU8xSzuATdBum7wFdiG6RoBAMvW7IainUo/1z0K26DILsEPiAFuaQoZ/S0rOLBI+jc/XX6fySG4862/J2M1Ma3cytR2nWRieco6oQvxubQcT6QboztahjCsSJXCRRblckRMPSrUNl3rbGb6BzVmTTP2+FkgSwLFhbkArMvJXEVVT0ROukpD0gQjwZbJW4A/Lp/lwJk8WRYXCvmETMc5cmpMHRDo6QAy6+MHHsqlosH16hFLeeOM1IQsa67i/ZcuCjr0nQz0PjvrrYl0JqVw=
install: npm install
before_script:
  - 'git config --global user.name "Travis-CI"'
  - 'git config --global user.email "myk@mykzilla.org"'
script: gulp
after_success:
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && [ "${TRAVIS_BRANCH}" = "master" ] && gulp deploy'
