language: node_js
node_js:
  - '0.10'
env:
  global:
    - secure: 1qrlptwaeTL1EAfenpeK000CLPOJrjnOVAWFsembZh9C8UbM6xOMUVimSzrb6UarcguRUlhjTSs+f5bUy/fRfLczrz5PRUdecKmLVvbQAq/TuvhV3UtbvQI27g9N2SPkT9WReMGbdIvu/uRlgm2t2e6LmhpWc1mzVjvd768ldyY354iQUxscGSCu05bz/ulSx9CJJUzFntxT/60pu9DoP3n+MxFlfrjNw8awluQNOQZQTSZ0waPG3J5GA5n8oWNR9DwzZ6Oppj3/RNrxSGeglKy0rhFGuPnGriezap5JUiSiJnRr55RIGiMjt3H9EcRfde2uPAhgOeiauPcUWXsZrxqCfxF6xcwLIMWtoue+V3cpSA+sspFdaShHtkUzkgBxKQW+u1SS9b3TerkZYtjinlsmXR8O2I19vMXTF7LwWPNmfv+RPXXD3OcEdlpRf7bMvS9fiCfPIBS1ZDxYs6oQXjzlAmHSgObywGqbGb+bSN56Jr5YRQzHKTyRFSXXoVzB0n+ZLUk8EVwSpHnD50GOKo//e2s1yQGQjUCZj1luTynGdOL1FSFr0/xH31YARDOFN0jDK6WAt8r22KruuRaGl3VK4ia44LHDBQ40XYaqYjq/YbZUjg/9+n4OtFi1UHZvHvh1R12wixT/yiHs1Ro+6Hx3biMwJutbCJj9zsRMnQY=
install: npm install
before_script:
  - 'git config --global user.name "Travis-CI"'
  - 'git config --global user.email "myk@mykzilla.org"'
script: gulp
after_success:
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && [ "${TRAVIS_BRANCH}" = "master" ] && gulp deploy'
