language: node_js
node_js:
  - '0.10'
env:
  global:
    - PLACEHOLDER: 'Fix the bug that requires this placeholder to add entries to this list!'
install: npm install
before_script:
  - 'git config --global user.name "Travis-CI"'
  - 'git config --global user.email "myk@mykzilla.org"'
script: gulp
after_success:
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && [ "${TRAVIS_BRANCH}" = "master" ] && gulp deploy'
